import type { Metadata } from 'next';
import { orbitron, audiowide, exo2 } from '@/lib/fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  authors: [
    { name: 'Luis Gustavo Sequeiros Condori', url: 'https://github.com/gusCreator' },
    { name: 'Christian Raúl Mestas Zegarra', url: 'https://github.com/cmestasz' },
    { name: 'Ryan Fabian Valdivia Segovia', url: 'https://github.com/RyanValdivia/' },
    { name: 'Álvaro Raúl Quispe Condori', url: 'https://github.com/ALVARO-QUISPE-UNSA/' },
    { name: 'Diego Alejandro Carbajal González', url: 'https://github.com/Gocardi' },
  ],
  applicationName: 'Exoplanets',
  keywords: 'exoplanets space nasa hackaton',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${orbitron.variable} ${audiowide.variable} ${exo2.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
